import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import localFont from "next/font/local";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
// import ToastProvider from "./providers/ToastProvider";


// const geistSans = localFont({
//   src: "../fonts/GeistVariable.woff2",
//   variable: "--font-geist-sans",
//    weight: "100 900",
// });

// const geistMono = localFont({
//    src: "../fonts/GeistMonoVariable.woff2",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>

    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <ToastProvider/> */}
        {children}
      </body>
    </html>
    </ClerkProvider>
  );
}
